language: php

env:
  - DB=mysql

before_script:
  - composer self-update
  - git clone https://github.com/glpi-project/glpi -b 9.1 ../glpi && cd ../glpi
  - composer install --no-dev
  - mysql -u root -e 'create database glpitest;'
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - mv ../fields plugins/fields
  - cd plugins/fields
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then sed -e "s|.*"consolidation/robo".*$||" -i composer.json && composer update; fi
  - composer install -o
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - mysql -u root -e 'select version();'
  - phpcs -p --ignore=vendor --ignore=js --standard=tools/phpcs-rules.xml  .
  - phpunit --verbose

matrix:
  include:
    - php: 5.4
      addons:
        mariadb: 5.5
    - php: 5.5
      addons:
        mariadb: 5.5
#    - php: 5.6
#      addons:
#        mariadb: 5.5
#    - php: 5.6
#      addons:
#        mariadb: 10.0
    - php: 5.6
      addons:
        mariadb: 10.1
#    - php: 7.0
#      addons:
#        mariadb: 10.0
    - php: 7.0
      addons:
        mariadb: 10.1
#    - php: 7.1
#      addons:
#        mariadb: 10.0
    - php: 7.1
      addons:
        mariadb: 10.1
    - php: nightly
      addons:
        mariadb: 10.1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#channel"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
